import Head from 'next/head'
import styles from '../styles/Curriculo.module.css'
import Link from 'next/link'
import {AiOutlinePhone, AiOutlineMail} from 'react-icons/ai'
import {GoLocation} from 'react-icons/go'
import {BiLinkAlt} from 'react-icons/bi'
import { Col,Row, Container,Image, Button } from 'react-bootstrap';
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import dadosCurriculo from './globals';


export default function Curriculo() {
  const data = dadosCurriculo 
  console.log(data)


  const printDocument = async () => {
    //gerar pdf do id divToPrint
    const input = document.getElementById('divToPrint');
    var opt = {
      margin:       0.2,
      filename:     `curriculo ${data.informacoesPessoais.nome} ${data.informacoesPessoais.sobrenome}.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2,allowTaint: true, useCORS: true }, 
      jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    };
    html2pdf().set(opt,{
      pagebreak: { mode: ['avoid-all'] }
    }).from(input).save();
    
  };

  var experiencia = []
  var projetosUsados = []
  var projetosExtras = []
  //percorrer o arquivo json
  for (var i = 0; i < data.experiencia.length; i++) {
    //adicionar o conteudo do arquivo json no array
    var projetos = []
    //deletar primeiro item do string data.experiencia[i].competencias
    var competencias = data.experiencia[i].competencias
    var competencias = competencias.substring(13, competencias.length)
    var empresa = data.experiencia[i].EmpresaTipo
    //remover tudo depois de \u00b7
    var empresa = empresa.substring(0, empresa.indexOf("\u00b7")-1)
    for (var j = 0; j < data.projetos.length; j++) {
      var associado = data.projetos[j].associado
      //remover string "Associado(s) a" de associado
      if(associado != null){
        associado = associado.substring(15, associado.length)  
        if(associado == empresa){
          projetosUsados.push(data.projetos[j])
          projetos.push(
          <div key={j}>
            <h5>{data.projetos[j].titulo}</h5>
            <p>{data.projetos[j].periodo}</p>
            <p>{data.projetos[j].descricao}</p>
            {data.projetos[j].link != null ? <a href={data.projetos[j].link} target="_blank">Link</a> : null}
            <div className={styles.linhaPontilhada}/>
          </div>
          )
        }
      }
    }

    experiencia.push(
      <div className={styles.cardContent}>
        <h5>{data.experiencia[i].cargo}</h5>
        <h5>{data.experiencia[i].EmpresaTipo}</h5>
        <p>{data.experiencia[i].periodo}</p>
        <p>{data.experiencia[i].localizacao}</p>

        {
        projetos.length > 0 ? 
        <div className={styles.projetos}>
          <h6>PROJETOS REALIZADOS:</h6>         
            {projetos}
        </div>
        : null
        }
        <p><b>Competências utilizadas:</b>{competencias}</p>

        <hr/>
      </div>
    )


  for (var i = 0; i < data.projetos.length; i++) {
    //verificar se o projeto nao esta na lista projetosUsados
    if(projetosUsados.indexOf(data.projetos[i]) == -1){
      projetosExtras.push(
        <div key={i}>
          <h5>{data.projetos[i].titulo}</h5>
          <p>{data.projetos[i].associado}</p>
          <p>{data.projetos[i].periodo}</p>
          <p>{data.projetos[i].descricao}</p>
          {data.projetos[i].link != null ?
         <Link href={`${data.projetos[i].link}`} target="_blank"><Button variant='dark'>Visualizar</Button></Link>
          : null}
          <hr/>
        </div>
        
      )
    }
  }
  }
  return (
    <div>
      <Head>
        <title>Currículo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      </Head>

      <main>
        <Button variant='dark' onClick={printDocument} id={styles.buttonDownload}>Download</Button>
        <Container className={styles.main} >
          <div id='divToPrint'>          
          <Row>
            <Col sm={8} className={styles.contatoInfo}>

              <span><h1>{data.informacoesPessoais.nome}</h1><h1 id={styles.sobrenome}>{data.informacoesPessoais.sobrenome}</h1></span>

              <p>
                {data.informacoesPessoais.cargo}
              </p>
              <ul>
                <li><AiOutlinePhone className={styles.iconeInfo}/>{data.informacoesPessoais.telefone}</li>
                <li><AiOutlineMail className={styles.iconeInfo}/>{data.informacoesPessoais.email}</li>
                <li><GoLocation className={styles.iconeInfo}/>{data.informacoesPessoais.localizacao}</li>
                <li><BiLinkAlt className={styles.iconeInfo}/><a href={`https://${data.informacoesPessoais.links[0]}`} target='_blank'>{data.informacoesPessoais.links[0]}</a></li>
              </ul>
            </Col>
            <Col>  
              <Image src={data.informacoesPessoais.imagem} roundedCircle/>
            </Col>
          </Row>
          <Row className={styles.conteudo}>
            <Col sm={8} className={styles.colunaEsquerda}>
              <div className={styles.cardContent}>
                <h3 >PERFIL</h3>
                <p >{data.sobre}</p>
              </div>

              <h3>EXPERIÊNCIA</h3>
              {experiencia}

              <h3>PROJETOS</h3>
              {projetosExtras}

            </Col>
              
            <Col>
              <h3>FORMAÇÃO</h3>
              {data.formacoes.map((item, index) => (
                <div key={index} className={styles.cardContent}>
                  <h5>{item.curso}</h5>
                  <p>{item.instituicao}</p>
                  <p>{item.periodo}</p>
                  <div className={styles.linhaPontilhada}/>
                </div>
              ))}

              <h3>IDIOMA</h3>
              {
                data.idiomas.map((item, index) => (
                  <div key={index} className={styles.cardContent}>
                    <h5>{item.nome}</h5>
                    <p>{item.nivel}</p>
                    <div className={styles.linhaPontilhada}/>
                  </div>
                ))
              }

              <h3>COMPETÊNCIAS</h3>

              <ul>
              {
                data.competencias.map((item, index) => (
                  <li key={index} className={styles.cardContent}>
                    <p>{item.nome}</p>
                  </li>
                ))
              }
              </ul>
              
            </Col>
          </Row>
          <Container className={styles.conteudo}>
            <h3>LICENÇAS E CERTIFICADOS</h3>
                {data.certificadosLicencas.map((item, index) => (
                  <div key={index} className={styles.cardContent}>
                    <h5>{item.titulo}</h5>
                    <p>{item.instituicao}</p>
                    <p>{item.periodo}</p>
                    <hr/>
                  </div>
              ))}
          </Container>
          </div>
        </Container>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
